# https://wandb.ai

wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: "mDDPM"
  name:  ${hydra:job.name}
  save_dir: "."
  offline: False # set True to store all logs only locally
  id: null # pass correct id to resume experiment!
  resume: False
  log_model: False
  prefix: ""
  job_type: ""
  group: ""
  tags: []
  # note: ""